### ISSUE TITLE
Add ScrollBar

### ISSUE THREAD

**Issue by jonnius** [bertoldia/files-menu#3]
Please add a scroll bar if the list of files is too long to be displayed!

**Comment by bertoldia** [comment]
You. Are. Awesome. You totally read my mind. I had started to look at this
but got busy with other stuff. I'll merge this asap.

Thanks!

**Comment by bertoldia** [comment]
Oh wait. I though this was a pull request! Still, issue acknowledged and a fix is (slowly) in the works.

**Comment by bertoldia** [comment]
Fixed by commit d5a17ebcd6e387f7f99e9c8a497bf3de8983965d
